<#@ template debug="false" hostspecific="false" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ import namespace="System" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ output extension=".cs" #>
<#@ include file="../Helpers.ttinclude" #>
using System;
using System.Collections.Generic;
using System.Linq;

namespace FuncSharp
{
    public static class Try
    {
        /// <summary>
        /// Tries the specified action and returns its result if it succeeds. Otherwise in case of the specified exception,
        /// returns result of the recovery function.
        /// </summary>
        public static A Catch<A, E>(Func<Unit, A> action, Func<E, A> recover)
            where E : Exception
        {
            try
            {
                return action(Unit.Value);
            }
            catch (E e)
            {
                return recover(e);
            }
        }

        /// <summary>
        /// Create a new try with the result of the specified function while converting exceptions of the specified type
        /// into erroneous result.
        /// </summary>
        public static Try<A, E> Create<A, E>(Func<Unit, A> f)
            where E : Exception
        {
            return Catch<Try<A, E>, E>(
                _ => Success(f(Unit.Value)),
                e => Error(e)
            );
        }

        /// <summary>
        /// Creates a new try with a successful result.
        /// </summary>
        public static SuccessTry<A> Success<A>(A value)
        {
            return new SuccessTry<A>(value);
        }

        /// <summary>
        /// Creates a new try with a successful result.
        /// </summary>
        public static Try<A, E> Success<A, E>(A value)
        {
            return new Try<A, E>(value);
        }

        /// <summary>
        /// Creates a new try with an error result.
        /// </summary>
        public static ErrorTry<E> Error<E>(E error)
        {
            return new ErrorTry<E>(error);
        }

        /// <summary>
        /// Creates a new try with an error result.
        /// </summary>
        public static Try<A, E> Error<A, E>(E error)
        {
            return new Try<A, E>(error);
        }

        /// <summary>
        /// Aggregates a collection of tries into a try of collection.
        /// </summary>
        public static Try<IEnumerable<A>, Exception> Aggregate<A, E>(IEnumerable<Try<A, E>> tries)
            where E : Exception
        {
            return Aggregate<A, E, Try<IEnumerable<A>, Exception>>(
                tries,
                t => Success(t),
                e => Error(e.Aggregate())
            );
        }

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates the errors by given aggregate and calls error function.
        /// </summary>
        public static R Aggregate<A, E, R>(IEnumerable<Try<A, E>> tries, Func<IEnumerable<A>, R> success, Func<IEnumerable<E>, R> error)
        {
            var enumeratedTries = tries.ToList();
            if (enumeratedTries.All(t => t.IsSuccess))
            {
                return success(enumeratedTries.Select(t => t.Success).Flatten().ToList());
            }

            return error(enumeratedTries.Select(t => t.Error).Flatten());
        }
<#  for (var i = 2; i < MaxFuncArity(); i++) { #>

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates the errors by given aggregate and calls error function.
        /// </summary>
        public static R Aggregate<<#= Types(i, name: "A") #>, E, R>(<#= List(i, x => $"Try<{Type(x, name: "A")}, E> t{x}") #>, Func<<#= Types(i, name: "A") #>, R> success, Func<IEnumerable<E>, R> error)
        {
            if (<#= List(i, x => $"t{x}.IsSuccess", separator: " && ") #>)
            {
                return success(<#= List(i, x => $"t{x}.Success.Get()") #>);
            }

            var errors = new[] { <#= List(i, x => $"t{x}.Error") #> };
            return error(errors.Flatten());
        }

        /// <summary>
        /// Aggregates the tries using the specified function if all of them are successful. Otherwise aggregates all exceptions into an AggregateException.
        /// </summary>
        public static Try<B, Exception> Aggregate<<#= Types(i, name: "A") #>, E, B>(<#= List(i, x => $"Try<A{x}, E> t{x}") #>, Func<<#= Types(i, name: "A") #>, B> f)
            where E : Exception
        {
            return Aggregate<<#= Types(i, name: "A") #>, E, Try<B, Exception>>(
                <#= List(i, x => $"t{x}") #>,
                (<#= List(i, x => $"s{x}") #>) => Success(f(<#= List(i, x => $"s{x}") #>)),
                e => Error(e.Aggregate())
            );
        }
<#  } #>
    }

    /// <summary>
    /// Result of an operation that may either succeed or fail with an error.
    /// </summary>
    public class Try<A, E> : Coproduct2<A, E>
    {
        internal Try(A success)
            : base(success)
        {
        }

        internal Try(E error)
            : base(error)
        {
        }

        /// <summary>
        /// Returns whether the result is a success.
        /// </summary>
        public bool IsSuccess
        {
            get { return IsFirst; }
        }

        /// <summary>
        /// Returns whether the result is an error.
        /// </summary>
        public bool IsError
        {
            get { return IsSecond; }
        }

        /// <summary>
        /// Returns the successful result.
        /// </summary>
        public Option<A> Success
        {
            get { return First; }
        }

        /// <summary>
        /// Returns the error result.
        /// </summary>
        public Option<E> Error
        {
            get { return Second; }
        }

        /// <summary>
        /// Maps the successful result to a new successful result.
        /// </summary>
        public Try<B, E> Map<B>(Func<A, B> f)
        {
            return Match<Try<B, E>>(
                s => Try.Success(f(s)),
                e => Try.Error(e)
            );
        }

        /// <summary>
        /// Maps the error result to a new error result.
        /// </summary>
        public Try<A, F> MapError<F>(Func<E, F> f)
        {
            return Match<Try<A, F>>(
                s => Try.Success(s),
                e => Try.Error(f(e))
            );
        }

        public static implicit operator Try<A, E>(SuccessTry<A> success)
        {
            return new Try<A, E>(success.Value);
        }

        public static implicit operator Try<A, E>(ErrorTry<E> error)
        {
            return new Try<A, E>(error.Value);
        }
    }
}
